services:
  mysql:
    image: mysql:8.0
    container_name: talentoplus-mysql
    environment:
      MYSQL_DATABASE: talentoplus_db
      MYSQL_USER: talentoplus
      MYSQL_PASSWORD: talentoplus123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3310:3306"   # <--- CAMBIADO (antes 3306 o 3307)
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    build:
      context: .
      dockerfile: TalentoP.Api/Dockerfile
    container_name: talentoplus-api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9001:8080"   # <--- CAMBIADO (antes 8081:8080)

  web:
    build:
      context: .
      dockerfile: TalentoP.Web/Dockerfile
    container_name: talentoplus-web
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      mysql:
        condition: service_healthy
      api:
        condition: service_started
    ports:
      - "9000:8080"   # <--- CAMBIADO (antes 8080:8080)

volumes:
  mysql_data:
